FROM ubuntu:22.04 as ubuntubuilder

RUN apt-get update \
  && apt-get install -y build-essential cmake curl g++ git luarocks \
  && curl -Lo "session-manager-plugin.deb" \
  "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" \
  && dpkg -i "session-manager-plugin.deb" \
  && luarocks install --server=https://luarocks.org/dev luaformatter

FROM docker.io/library/archlinux:base-devel

LABEL com.github.containers.toolbox="true" \
  name="archlinux-toolbox" \
  version="base-devel" \
  usage="This image is meant to be used with the toolbox or distrobox command" \
  summary="Base image for creating Arch Linux toolbox containers" \
  maintainer="scott@ames.sh"

COPY extra-packages /

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN pacman -Syu --needed --noconfirm - < extra-packages && \
  printf "LANG=en_US.UTF-8\nLANGUAGE=en_US" | tee /etc/locale.conf && \
  sed -i '/\#en_US.UTF-8 UTF-8/{s/#//g;s/@/-at-/g;}' /etc/locale.gen && \
  locale-gen && \
  rm /extra-packages && \
  pacman -Scc --noconfirm && \
  echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox

COPY --from=ubuntubuilder \
  /usr/local/sessionmanagerplugin/bin/session-manager-plugin \
  /usr/local/bin/lua-format \
  /usr/local/bin/

RUN \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/hostnamectl && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/loginctl && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/nmcli && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/op && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/systemctl && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/xclip && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
