FROM registry.fedoraproject.org/fedora-toolbox:41 AS fedora-distrobox

LABEL com.github.containers.toolbox="true" \
  usage="This image is meant to be used with the toolbox or distrobox command" \
  summary="A cloud-native terminal experience powered by Fedora"

COPY extra-packages /

# Set up distrobox dependencies
RUN git clone https://github.com/89luca89/distrobox.git --single-branch /tmp/distrobox && \
  cp /tmp/distrobox/distrobox-host-exec /usr/bin/distrobox-host-exec && \
  wget https://github.com/1player/host-spawn/releases/download/$(cat /tmp/distrobox/distrobox-host-exec | grep host_spawn_version= | cut -d "\"" -f 2)/host-spawn-$(uname -m) -O /usr/bin/host-spawn && \
  chmod +x /usr/bin/host-spawn && \
  rm -drf /tmp/distrobox

RUN dnf -y upgrade && \
  dnf -y install $(<extra-packages) && \
  dnf install -y \
  https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm && \
  dnf install -y \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
  dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld && \
  dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld && \
  dnf clean all

RUN \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/hostnamectl && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/loginctl && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/nmcli && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/op && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/systemctl && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/xclip && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open

RUN rm /extra-packages
