FROM docker.io/library/archlinux:base-devel

LABEL com.github.containers.toolbox="true" \
    name="archlinux-toolbox" \
    version="base-devel" \
    usage="This image is meant to be used with the toolbox or distrobox command" \
    summary="Base image for creating Arch Linux toolbox containers" \
    maintainer="scott@ames.sh"

COPY extra-packages /

RUN pacman -Syu --needed --noconfirm - < extra-packages && \
    printf "LANG=en_US.UTF-8\nLANGUAGE=en_US" | tee /etc/locale.conf && \
    sed -i '/\#en_US.UTF-8 UTF-8/{s/#//g;s/@/-at-/g;}' /etc/locale.gen && \
    locale-gen && \
    rm /extra-packages && \
    pacman -Scc --noconfirm \
    echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox

