name: "Build and push images"
on:
  push:
    branches:
      - main
    paths:
      - toolbox/**
      - .github/workflows/build-and-push.yaml
  schedule:
    - cron: '0 0 * * TUE'
concurrency: ${{ github.workflow }}
env:
  REGISTRY_DOMAIN: ghcr.io
  REGISTRY_OWNER: ${{ github.repository_owner }}
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./toolbox/archlinux
            image: archlinux-toolbox
            distro: archlinux
            image_pretty: Arch Linux - Toolbox
            tags: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ matrix.image }}
      - name: Build
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ${{ matrix.context }}/Containerfile
          context: ${{ matrix.context }}
          image: ${{ matrix.image }}
          tags: ${{ matrix.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false
      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.REGISTRY_DOMAIN }}/${{ env.REGISTRY_OWNER }}
      - name: Push
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_DOMAIN }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Sign container
      - uses: sigstore/cosign-installer@v3
      - name: Sign container image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY \
            ${{ steps.registry_case.outputs.lowercase }}/${{ matrix.image }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      - name: Outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
